import fs from 'node:fs';
import vm from 'node:vm';
const root=new URL('.',import.meta.url);
const manifest=JSON.parse(fs.readFileSync(new URL('content/manifest.json',root),'utf8'));
const rows=manifest.batches.flatMap(({file,expected,count})=>{
  const required=count??expected;
  const entries=JSON.parse(fs.readFileSync(new URL(`content/${file}`,root),'utf8'));
  if(entries.length!==required)throw new Error(`${file}: expected ${required}, received ${entries.length}`);
  return entries;
});
const context={window:{}};vm.runInNewContext(fs.readFileSync(new URL('data.js',root),'utf8'),context);
const ids=new Set(context.window.DICTIONARY.map(e=>e.id));
const terms=new Set(context.window.DICTIONARY.map(e=>e.term.toLowerCase()));
const categories=new Set(context.window.CATEGORIES.map(c=>c[0]));
const slug=t=>t.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-$/,'');
for(const row of rows){
  const id=row.id||slug(row.term);
  if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(id))throw new Error(`Invalid slug: ${id}`);
  if(ids.has(id)||terms.has(row.term.toLowerCase()))throw new Error(`Duplicate: ${row.term} (${id})`);
  ids.add(id);terms.add(row.term.toLowerCase());
  for(const field of ['term','fullName','arabicName','definition','example','whereUsed','category','level'])if(typeof row[field]!=='string'||!row[field].trim())throw new Error(`${row.term}: missing ${field}`);
  if(!categories.has(row.category))throw new Error(`${row.term}: unknown category`);
  if(!['Beginner','Intermediate','Advanced'].includes(row.level))throw new Error(`${row.term}: invalid level`);
  if(!Array.isArray(row.en)||row.en.length!==3||row.en.some(s=>typeof s!=='string'||!s.trim()))throw new Error(`${row.term}: incomplete English copy`);
  if(!Array.isArray(row.relatedTerms)||!row.relatedTerms.length)throw new Error(`${row.term}: missing related terms`);
  if(!Array.isArray(row.aliases)||!Array.isArray(row.sources))throw new Error(`${row.term}: missing aliases/sources arrays`);
  for(const source of row.sources){const url=new URL(source);if(!['https:','http:'].includes(url.protocol))throw new Error(`${row.term}: invalid source protocol`)}
}
for(const row of rows)for(const related of row.relatedTerms)if(!ids.has(related))throw new Error(`${row.term}: unknown related term ${related}`);
if(ids.size!==manifest.currentReleaseCount)throw new Error(`Expected ${manifest.currentReleaseCount} distinct terms; got ${ids.size}`);
if(Object.values(manifest.targetDistribution).reduce((sum,count)=>sum+count,0)!==manifest.collectionGoal)throw new Error('Target category distribution does not equal the collection goal.');
const output=`// Generated by build-content.mjs from content/*.json. Edit the source JSON files.\n(()=>{\nconst entries=${JSON.stringify(rows)};\nfor(const row of entries){\nconst id=row.id||row.term.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-$/,'');\nwindow.DICTIONARY.push({id,slug:id,term:row.term,type:/^[A-Z][A-Z0-9/]*$/.test(row.term)?'acronym':'term',fullName:row.fullName,arabicName:row.arabicName,aliases:row.aliases,category:row.category,subcategory:'',level:row.level,shortDefinition:row.definition,simpleExplanation:row.definition,example:row.example,whereUsed:row.whereUsed,relatedTerms:row.relatedTerms,alternateMeanings:[],keywords:row.keywords||[],sources:row.sources,reviewStatus:row.reviewStatus||'editorial',lastReviewed:'2026-09-30'});\nwindow.EN_CONTENT[id]=row.en;\n}\n})();\n`;
fs.writeFileSync(new URL('expansion.js',root),output);
console.log(`Built ${rows.length} expansion entries; ${ids.size} total. Collection goal: ${manifest.collectionGoal}.`);
