// English editorial copy for each canonical dictionary entry: definition, example, where used.
window.EN_CONTENT={
  ai:['Technology that lets computers perform tasks normally requiring human intelligence, such as understanding text or recognizing images.','An app identifies cats in photos.','Smart assistants, search, and everyday apps.'],
  api:['A defined way for one program to request data or a service from another program.','A weather app asks a weather service for today’s temperature.','Connecting apps and online services.'],
  rag:['A method that finds relevant information from selected sources before a model writes its answer.','An assistant reads a company handbook before answering a leave-policy question.','Assistants that answer from documents.'],
  llm:['A system trained on large amounts of text to understand and generate language.','An assistant drafts an email or summarizes an article.','Writing assistants, search, and translation.'],
  mcp:['A standard way for AI applications to connect to tools and external data sources.','With permission, an assistant reads a file through an MCP-compatible tool.','Connecting AI assistants to tools.'],
  kubernetes:['A system that organizes containers across computers, monitors them, and adds more when needed.','An online shop runs extra app copies during a sale.','Operating large applications.'],
  docker:['A tool that packages an application and its requirements in a container so it runs consistently elsewhere.','A developer moves an app from a laptop to a server in a container.','Developing and deploying apps.'],
  vpn:['An encrypted connection between your device and another server that helps protect data in transit.','An employee connects to the company network from home.','Remote work and secure connections.'],
  agi:['A proposed AI system that could learn and work flexibly across many domains; there is no agreed example today.','A hypothetical system learns a new task without task-specific training.','Discussions about the future of AI.'],
  sdk:['A set of tools and instructions that helps developers use a service or build for a platform.','A payment provider supplies an SDK for adding checkout.','App development.'],
  cli:['A way to control software by typing commands rather than clicking buttons.','Type a command to list files in a folder.','Developer tools and system administration.'],
  gui:['The screens, buttons, and menus that let people use software visually.','Desktop windows and icons.','Phones, computers, and apps.'],
  mvp:['A simple product version with the core value needed to test an idea with real users.','A booking app launches with booking as its only feature.','Early product launches.'],
  poc:['A small experiment to check whether a technical idea is feasible.','Test automatic document reading before building a full product.','Before committing to a larger project.'],
  saas:['Software used over the internet, often by subscription, without managing its installation yourself.','An accounting app that runs in a browser.','Cloud-based work tools.'],
  http:['Rules used by browsers and servers to exchange web pages and data.','A browser requests a page from a website.','Web addresses and app connections.'],
  https:['HTTP with encryption that protects data while it travels between browser and server.','A site uses HTTPS when you submit a password.','Secure websites.'],
  dns:['A system that translates a website name into a network address computers can reach.','It finds the server address for imhotip.com.','Opening websites.'],
  cpu:['The computer component that carries out general program instructions.','It processes instructions when you open an app.','Computer and phone specifications.'],
  gpu:['A processor good at many similar calculations at once, including graphics and some AI tasks.','It speeds up a game or AI model training.','Games, graphics, and AI.'],
  ram:['Temporary memory that holds data programs need while running; it clears when power is off.','Opening more apps uses more RAM.','Device specifications.'],
  ssd:['Fast permanent storage that keeps files and programs when the device is off.','A computer starts faster when its system is on an SSD.','Computers and storage.'],
  sql:['A language for asking for and changing data in relational databases.','Request customers who bought something this month.','Databases and data analysis.'],
  nosql:['A family of databases that use data models other than traditional relational tables.','Store JSON documents in a database.','Apps with flexible data models.'],
  json:['A structured text format for exchanging data between programs, not limited to JavaScript.','Send a user’s name and age from an app to a server.','APIs and configuration files.'],
  rest:['Common design principles for web services that expose resources through web addresses and requests.','Request a product list from a defined URL.','Designing APIs.'],
  git:['A tool that records file changes over time and helps people collaborate on code.','Return to an earlier version after a mistake.','Software development.'],
  'ci-cd':['A practice that automates checking, preparing, and frequently delivering software changes.','Tests run automatically when code is uploaded.','Software development teams.'],
  cloud:['Using computing services over the internet instead of running everything on your own device.','Store a file online and open it on a phone or computer.','Storage and application hosting.'],
  agent:['A program that uses an AI model and tools to take steps toward a goal within user-defined limits.','An assistant searches permitted files and prepares a summary.','Task automation and assistants.'],
  prompt:['The text or other input you give an AI model to describe what you want.','Ask: Summarize this article in three points.','Using AI tools.'],
  token:['A small unit of text a language model processes; it can be a word or part of one.','A long word may be split into several tokens.','Model limits and capacity.'],
  embedding:['Numbers that represent content so a computer can compare how similar meanings are.','Find documents similar in meaning to a question.','Semantic search and RAG.'],
  'vector-db':['A database that stores numerical representations and quickly finds similar items.','Find passages close in meaning to a question.','Semantic search and RAG.'],
  inference:['Using a trained model to produce a result for new input.','Give a model a photo to identify its contents.','Running AI models.'],
  tps:['For language models, a speed measure: how many text tokens are produced each second.','A model produces 50 tokens in one second.','Comparing model speed.'],
  container:['A relatively isolated package containing an app and what it needs to run.','Run the same app in a container on a new server.','Deploying applications.'],
  webhook:['A way for one system to send another an automatic web request when an event happens.','A shop alerts its shipping system after an order is confirmed.','Connecting services.'],
  framework:['A ready-made structure and tools for building software in an organized way.','A web framework provides a way to create pages.','App development.'],
  cache:['A temporary saved copy of data that makes future access faster.','A browser keeps a logo image instead of downloading it every time.','Browsers, apps, and servers.'],
  repository:['A place that holds project files and usually their change history through Git.','A website repository contains its code and assets.','Collaborative software work.'],
  branch:['A separate line of work in a Git project that can later be merged.','Create a branch for a new search feature.','Software development.'],
  commit:['A recorded snapshot of file changes in a Git project.','Save a bug fix with a message describing it.','Tracking code changes.'],
  dataset:['An organized collection of examples or records used for analysis or model training.','A table of daily weather measurements.','Analytics and AI.'],
  testing:['Checking that software works as expected in different situations.','Test that search returns the right term.','Before and after releasing changes.']
};
